question_data = [
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "Nutella is produced by the German company Ferrero.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "hard",
            "category": "History",
            "question": "The Kingdom of Prussia briefly held land in Estonia.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Television",
            "question": "In 'Star Trek', Klaang is a typical Klingon male.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Video Games",
            "question": "In the Season One Championship of &quot;League of Legends&quot;, the highest achievable rank was Diamond.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "hard",
            "category": "History",
            "question": "Japan was part of the Allied Powers during World War I.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "General Knowledge",
            "question": "The French word to travel is &quot;Travail&quot;",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Television",
            "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "hard",
            "category": "Science: Mathematics",
            "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Animals",
            "question": "Rabbits are rodents.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ]
